name: Deploy Cloud Functions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Deploy to gen2 cloud function'
        run:  |
          gcloud functions deploy gcloud-cloud-function \
          --gen2 \
          --region=us-central1 \
          --runtime=python310 \
          --source=src \
          --entry-point=<hello_world \
          --trigger-http \
          --project='${{ secrets.GCP_PROJECT_ID }}'