name: Deploy Cloud Functions
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP 1'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/104429179211/locations/global/workloadIdentityPools/githubactions-workload-pool/providers/githubactions-workload-provider'
          service_account: 'employee-finder-407218@appspot.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list --project employee-finder-407218